### ISSUE TITLE
Let abort return never

### ISSUE THREAD

**Issue by oxc** [loathers/kolmafia-js#4]
Since abort immediately returns, it should be declared with return type never. That lets TypeScript smart cast values that have been guarded by an abort, because it knows that function never returns. For example:

```typescript
  const match = regexp.exec(text);
  if (!match) kolmafia.abort('Expected to find match.');
  const ix = match[1]; // fails --> TS2531: Object is possibly 'null'.
```

If `kolmafia.abort` returned `never`, this would compile as expected, while still being fully type-safe.

(This was the first example I had at hand, let me know if you need a better one.)

**Comment by gausie** [comment]
Thanks! This is now the case in v1.1.1

**Comment by oxc** [comment]
Cool, thanks!
